# Transcription Factor Project - KOLF2.1J Dataset Downstream Analysis
**Robin Anwyl, UCSD Subramaniam Lab**

**Goal:** Analyze the KOLF2.1J Perturb-seq dataset from the Nourreddine et al. (2024) preprint to investigate the effects of transcription factor knockdowns (TF KDs)

**Guiding Questions:** What do TF KD effects reveal about:
* the transcriptional regulatory network of hiPSCs? 
* TF crosstalk and co-regulation?
* cell lineage?
* how TFs influence chromatin remodeling?

# Import statements

Using psp_env virtual env

In [1]:
import sys
import os
psp_root = "/home/ranwyl/KOLF2.1J_Perturbation_Cell_Atlas/"
if psp_root not in sys.path:
    sys.path.insert(0, psp_root)

import psp

In [2]:
import anndata as ad
import numpy as np
import pandas as pd
import decoupler as dc
import gseapy as gp
from tqdm_joblib import tqdm_joblib
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("white")
from biothings_client import get_client

In [3]:
filepath = "/home/ranwyl/data_tf_project/KOLF_Pan_Genome_Alpha_CPMnorm_KD_ETest_Gene_gRNA_Filtered.h5ad"
adata = psp.utils.read_anndata(filepath)
adata

AnnData object with n_obs × n_vars = 54766 × 16115
    obs: 'gRNA', 'n_gRNA', 'n_gRNA_UMIs', 'gene_target', 'celltype', 'perturbation_type', 'n_UMI_counts', 'n_genes', 'perturbed', 'channel', 'perturbation', 'gene_target_ensembl_id', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'gene_target_expression (CPM)', 'NTC_target_gene_expression (CPM)', 'target_knockdown', 'perturbation_edist', 'perturbation_pvalue', 'perturbation_significant'
    var: 'gene_ids', 'feature_types', 'n_UMI_counts', 'n_cells', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'etest_results', 'etest_results_params'
    layers: 'counts'

In [4]:
filepath_pkl = "/home/ranwyl/results_tf_project/DE_results_matched_gene_target_DGE_GSEA_filt_lfc_shrink_renamed.pkl"
de_results = pd.read_pickle(filepath_pkl)
de_results.head()

,ZNF14_baseMean,ZNF14_log2FoldChange,ZNF14_lfcSE,ZNF14_stat,ZNF14_pvalue,ZNF14_padj,OSR2_baseMean,OSR2_log2FoldChange,OSR2_lfcSE,OSR2_stat,...,TBPL1_lfcSE,TBPL1_stat,TBPL1_pvalue,TBPL1_padj,NANOGP8_baseMean,NANOGP8_log2FoldChange,NANOGP8_lfcSE,NANOGP8_stat,NANOGP8_pvalue,NANOGP8_padj
A1BG,1.864257,0.326745,0.963938,0.621605,0.534201,0.999792,2.930308,-0.246638,0.785534,-0.480026,...,0.984034,0.156928,0.875302,0.998861,0.647072,-0.300694,1.143266,-0.655867,0.511910,0.986184
A1BG-AS1,0.373367,-0.507322,1.303229,-0.829939,0.406573,0.999792,0.156276,-0.199710,1.192319,-0.312614,...,1.696760,0.596046,0.551144,0.998861,0.506852,0.480127,1.952652,0.909238,0.363224,0.986184
A2M,0.512672,-0.283313,1.178650,-0.602808,0.546637,0.999792,0.316562,0.440787,1.667653,0.667365,...,1.304825,1.117027,0.263983,0.998861,0.143634,-0.148727,1.154294,-0.204839,0.837698,0.986184
A2ML1,0.891141,-0.208276,1.136526,-0.485204,0.627531,0.999792,1.680654,-0.047415,1.028004,-0.100598,...,1.254417,0.305428,0.760040,0.998861,0.497277,0.140608,1.391123,0.387270,0.698556,0.986184
A2ML1-AS1,2.926793,0.078209,0.935879,0.152192,0.879035,0.999792,5.159437,-0.145540,0.725942,-0.292408,...,0.911649,0.573533,0.566284,0.998861,1.794077,0.186223,0.901525,0.362423,0.717036,0.986184

In [5]:
leiden_clusters_filepath = "/home/ranwyl/output_files_tf_project/leiden_clusters_2-18-26.csv"
leiden_clusters = pd.read_csv(leiden_clusters_filepath, header=0, index_col=0)
leiden_clusters.head(3)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,BARHL1,DEAF1,ASCL5,CDX1,ARHGAP35,DMRT2,BACH1,ADNP2,BATF,ARID3B,...,ARX,ARNT2,ETV3L,EMX1,ETS1,E2F1,ATOH1,BHLHE41,ATF4,EBF2
1,E2F6,DMBX1,ATF1,EOMES,ARID2,FOSL2,CREB1,ATMIN,BBX,ESRRB,...,ATF3,CBX2,HNF4A,GATA1,FOXH1,MTERF1,KLF4,DUXA,CAMTA2,GTF2IRD1
2,FOXL1,ESRRG,ATOH7,ETV6,DLX4,FOXJ1,FOXE3,CHAMP1,BCL6B,HEY2,...,BARX1,CTCFL,MBD1,GATA5,HIC1,MTERF3,NFIL3,GLI4,CENPX,SNAPC4

In [8]:
leiden_clusters.tail(3)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
31,ZNF804A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,ZNF813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,ZSCAN5B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# TF target dict

import pickle

tf_target_dict_filepath = "/home/ranwyl/reference_tf_project/tf_target_signed_interactions.pkl"
with open(tf_target_dict_filepath, 'rb') as f: # binary read mode
    tf_target_interactions_dict = pickle.load(f)

# Filter Entrez genes for Pathview (using DGE results)

In [6]:
def filter_rename_entrez_genes(de_df: pd.DataFrame) -> pd.DataFrame:
    """
    Rename genes in DGE results DF by Entrez ID and remove genes
    without an Entrez ID.
    """
    all_genes = de_df.index.tolist()
    mygene = get_client('gene')
    # Query genes by symbol and Ensembl ID
    mg_results_df = mygene.querymany(all_genes, scopes="symbol,ensemblgene",
                                     field="entrezgene", species="human",
                                     entrezonly=True, as_dataframe=True)
    # Remove duplicates
    mg_results_df = mg_results_df.loc[~mg_results_df.index.duplicated(keep=False)]
    # First set of genes to rename
    found_mg_results_df = mg_results_df[mg_results_df["entrezgene"].notna()]
    gene_entrez_rename_dict1 = found_mg_results_df["entrezgene"].to_dict()

    # Query genes that were not found by alias
    genes_not_found = mg_results_df[mg_results_df["notfound"] == True].index.tolist()
    mg_alias_results_df = mygene.querymany(genes_not_found, scopes="alias", 
                                           field="entrezgene", species="human", 
                                           entrezonly=True, as_dataframe=True)
    # Remove duplicates
    mg_alias_results_df = \
        mg_alias_results_df.loc[~mg_alias_results_df.index.duplicated(keep=False)]
    # Second set of genes to rename
    found_mg_alias_results_df = mg_alias_results_df[mg_alias_results_df["entrezgene"].notna()]
    gene_entrez_rename_dict2 = found_mg_alias_results_df["entrezgene"].to_dict()

    # Rename genes
    gene_entrez_rename_dict = gene_entrez_rename_dict1 | gene_entrez_rename_dict2
    de_df_renamed = de_df[de_df.index.isin(gene_entrez_rename_dict.keys())]
    de_df_renamed = de_df_renamed.rename(index=gene_entrez_rename_dict)
    return de_df_renamed

In [47]:
de_results.shape

(16115, 2100)

In [48]:
de_df_entrez = filter_rename_entrez_genes(de_results)

2026-03-19 19:39:16 | [WARNING] Input sequence provided is already in string format. No operation performed
2026-03-19 19:39:16 | [INFO] querying 1-1000 ...
2026-03-19 19:39:17 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:18 | [INFO] querying 1001-2000 ...
2026-03-19 19:39:19 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:20 | [INFO] querying 2001-3000 ...
2026-03-19 19:39:21 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:22 | [INFO] querying 3001-4000 ...
2026-03-19 19:39:23 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:24 | [INFO] querying 4001-5000 ...
2026-03-19 19:39:25 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:26 | [INFO] querying 5001-6000 ...
2026-03-19 19:39:27 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:28 | [INFO] querying 6001-7000 ...
2026-03-19 19:39:29 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:30 | [INFO] querying 7001-8000 ...
2026-03-19 19:39:31 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:32 | [INFO] querying 8001-9000 ...
2026-03-19 19:39:33 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:34 | [INFO] querying 9001-10000 ...
2026-03-19 19:39:35 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:36 | [INFO] querying 10001-11000 ...
2026-03-19 19:39:37 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:38 | [INFO] querying 11001-12000 ...
2026-03-19 19:39:39 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:40 | [INFO] querying 12001-13000 ...
2026-03-19 19:39:41 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:42 | [INFO] querying 13001-14000 ...
2026-03-19 19:39:43 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:44 | [INFO] querying 14001-15000 ...
2026-03-19 19:39:45 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:46 | [INFO] querying 15001-16000 ...
2026-03-19 19:39:47 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:48 | [INFO] querying 16001-16115 ...
2026-03-19 19:39:48 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:49 | [INFO] Finished.
2026-03-19 19:39:50 | [WARNING] 2 input query terms found dup hits:	[('GOLGA2P5', 2), ('TEC', 2)]
2026-03-19 19:39:50 | [WARNING] 1234 input query terms found no hit:	['ADAL', 'ARMT1', 'B3GNTL1', 'BMT2', 'BVES', 'C10orf82', 'C11orf54', 'C11orf80', 'C12orf29', 'C12orf
2026-03-19 19:39:50 | [INFO] Pass "returnall=True" to return complete lists of duplicate or missing query terms.
2026-03-19 19:39:50 | [WARNING] Input sequence provided is already in string format. No operation performed
2026-03-19 19:39:50 | [INFO] querying 1-1000 ...
2026-03-19 19:39:51 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:52 | [INFO] querying 1001-1234 ...
2026-03-19 19:39:52 | [INFO] HTTP Request: POST https://mygene.info/v3/query/ "HTTP/1.1 200 OK"
2026-03-19 19:39:53 | [INFO] Finished.
2026-03-19 19:39:53 | [WARNING] 5 input query terms found dup hits:	[('C17orf49', 2), ('C18orf21', 2), ('CIR1', 2), ('NDUFA4', 2), ('TDGF1', 2)]
2026-03-19 19:39:53 | [WARNING] 1113 input query terms found no hit:	['DNAJC9-AS1-1', 'ENSG00000176868', 'ENSG00000183308', 'ENSG00000197462', 'ENSG00000197585', 'ENSG00
2026-03-19 19:39:53 | [INFO] Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [49]:
de_df_entrez.shape

(14994, 2100)

In [50]:
filepath_pkl = "/home/ranwyl/results_tf_project/DE_results_matched_gene_target_DGE_GSEA_filt_lfc_shrink_entrez.pkl"
de_df_entrez.to_pickle(filepath_pkl)

# TF-target dict

In [11]:
def build_tf_target_dict_signed(source_list: list[str] = ["CollecTRI", "DoRothEA", 
                                                          "TF_Perturbations_Followed_by_Expression",
                                                          "TF-LOF_Expression_from_GEO"], 
                                tfs_to_rename_dict: dict[str, list] | None = None, 
                                dorothea_levels=["A", "B", "C"]) -> dict[str, dict[str, set[str]]]:
    """
    Build dict {TF: {"UP": set of upreg genes, "DOWN": set of downreg genes}}
    using decoupler and gseapy.
    """
    all_dicts = list()

    if "CollecTRI" in source_list:
        collectri_df = dc.op.collectri(organism='human')
        collectri_dict = dict()
        for tf, gene, weight in collectri_df.iloc[:,:3].itertuples(index=False, name=None):
            if tf not in collectri_dict:
                collectri_dict[tf] = {"UP":set(), "DOWN":set()}
            if weight > 0: # TF is activator --> gene is downregulated
                collectri_dict[tf]["DOWN"].add(gene)
            else: # TF is repressor --> gene is upregulated
                collectri_dict[tf]["UP"].add(gene)
        all_dicts.append(collectri_dict)
    
    if "DoRothEA" in source_list:
        dorothea_df = dc.op.dorothea(organism='human', levels=dorothea_levels)
        dorothea_dict = dict()
        for tf, gene, weight in dorothea_df.iloc[:,:3].itertuples(index=False, name=None):
            if tf not in dorothea_dict:
                dorothea_dict[tf] = {"UP":set(), "DOWN":set()}
            if weight > 0:
                dorothea_dict[tf]["DOWN"].add(gene)
            else:
                dorothea_dict[tf]["UP"].add(gene)
        all_dicts.append(dorothea_dict)

    # Perturbation and LOF Enrichr libraries
    ko_lof_lib_list = list()
    if "TF_Perturbations_Followed_by_Expression" in source_list:
        pert_lib = gp.get_library(name="TF_Perturbations_Followed_by_Expression")
        ko_lof_lib_list.append(pert_lib)
    if "TF-LOF_Expression_from_GEO" in source_list:
        lof_lib = gp.get_library("TF-LOF_Expression_from_GEO")
        ko_lof_lib_list.append(lof_lib)
    if ko_lof_lib_list:
        ko_lof_dict = dict()
        for lib in ko_lof_lib_list:
            for tf_label, genes in lib.items():
                tf_label = tf_label.upper()
                if "HUMAN" in tf_label:
                    tf_label = tf_label.split(" ")
                    tf, reg = tf_label[0], tf_label[-1]
                    if tf not in ko_lof_dict:
                        ko_lof_dict[tf] = {"UP":set(), "DOWN":set()}
                    if reg == "UP":
                        ko_lof_dict[tf]["UP"].update(set(genes))
                    elif reg == "DOWN":
                        ko_lof_dict[tf]["DOWN"].update(set(genes))
        if tfs_to_rename_dict:
            for old_name, new_name in tfs_to_rename_dict.items():
                if new_name == "":
                    ko_lof_dict.pop(old_name)
                else:
                    ko_lof_dict[new_name] = ko_lof_dict.pop(old_name)
        all_dicts.append(ko_lof_dict)

    # Combine
    if len(all_dicts) == 1:
        return all_dicts[0]
    all_tfs = {tf for target_dict in all_dicts for tf in target_dict.keys()}
    all_tf_targets_dict = {tf: {"UP": set(), "DOWN": set()} for tf in all_tfs}
    for tf in all_tfs:
        genes_up = {g for target_dict in all_dicts if tf in target_dict for g in target_dict[tf]["UP"]}
        genes_down = {g for target_dict in all_dicts if tf in target_dict for g in target_dict[tf]["DOWN"]}
        all_tf_targets_dict[tf]["UP"].update(genes_up)
        all_tf_targets_dict[tf]["DOWN"].update(genes_down)
    return all_tf_targets_dict

In [15]:
import pickle

In [13]:
tfs_rename_dict = {"NCOA":"", "RENT1":"UPF1", "HIF2A":"EPAS1"} # old name : new name
tf_target_interactions_dict = build_tf_target_dict_signed(
    ["CollecTRI", "DoRothEA", "TF_Perturbations_Followed_by_Expression", "TF-LOF_Expression_from_GEO"], 
    tfs_to_rename_dict=tfs_rename_dict)

2026-03-05 14:31:34 | [INFO] Downloading and generating Enrichr library gene sets...
2026-03-05 14:31:54 | [INFO] Downloading and generating Enrichr library gene sets...
2026-03-05 14:32:16 | [INFO] 0017 gene_sets have been filtered out when max_size=2000 and min_size=0

Save as pickle

In [ ]:
tf_target_dict_filepath = "/home/ranwyl/reference_tf_project/tf_target_signed_interactions.pkl"
with open(tf_target_dict_filepath, 'wb') as f: # binary write mode
    pickle.dump(tf_target_interactions_dict, f)

# Cluster-level GSEA

In [ ]:
def prerank_gsea_cluster_kds(cluster_label: int | str,
                             cluster_kds: list[str], 
                             DE_results: pd.DataFrame, 
                             gene_set_lib: str, 
                             rank_by: str="stat",
                             min_term_size: int=5, 
                             max_term_size: int=1000, 
                             permutation_num: int=1000, 
                             n_cpus_per_cluster: int=4,
                             random_seed: int=42, 
                             verbose: bool=False) -> pd.DataFrame:
    """
    Run pre-ranked GSEA using the given Enrichr library on each 
    individual KD in a cluster. By default, rank genes by 
    Wald test statistic. min_size and max_size control Enrichr term size.
    """
    kd_prerank_results_dict = dict()
    for kd in cluster_kds:
        # Rank genes for KD
        rank_df = pd.DataFrame(DE_results[f"{kd}_{rank_by}"].values,
                               columns=[rank_by],
                               index=DE_results.index)
        rank_df.dropna(axis="index", inplace=True) # Drop NaN values
        rank_df.index.name = "gene"
        rank_df.sort_values(by=rank_by, ascending=False, inplace=True)
        # Run pre-ranked GSEA
        kd_prerank_result = \
            gp.prerank(rnk=rank_df,
                        gene_sets=gene_set_lib,
                        threads=n_cpus_per_cluster,
                        min_size=min_term_size,
                        max_size=max_term_size,
                        permutation_num=permutation_num,
                        outdir=None,
                        seed=random_seed,
                        verbose=verbose,
                        )
        # Add result to dict
        kd_prerank_results_dict[kd] = kd_prerank_result
    
    prerank_res_df_list = list()
    for kd in kd_prerank_results_dict:
        # Build results DF for KD
        kd_res_df = kd_prerank_results_dict[kd].res2d.copy()
        kd_res_df.insert(0, "KD", [kd]*kd_res_df.shape[0])
        kd_res_df.drop(columns=["Name"], inplace=True)
        prerank_res_df_list.append(kd_res_df)
    # Build results DF for cluster
    cluster_prerank_res_df = pd.concat(prerank_res_df_list)
    cluster_prerank_res_df.insert(0, "Cluster", 
                                  [cluster_label]*cluster_prerank_res_df.shape[0])
    return cluster_prerank_res_df

def prerank_gsea_all_clusters(cluster_df: pd.DataFrame, 
                              DE_results: pd.DataFrame, 
                              gene_set_lib: str, 
                              min_term_size: int=5, 
                              max_term_size: int=1000, 
                              permutation_num: int=1000, 
                              n_cpus_per_cluster: int=4, 
                              n_jobs_parallel: int=10,
                              random_seed: int=42, 
                              verbose: bool=False,
                              rank_by: str = "stat",
                              ) -> pd.DataFrame:
    """
    Run pre-ranked GSEA on all KDs using the given Enrichr library.
    Build a results DF where each term is labeled by KD and cluster.
    """
    cluster_kd_dict = {cl: list(cluster_df[cl][cluster_df[cl].notna()])
                       for cl in cluster_df.columns}   
    
    with tqdm_joblib(desc="Running pre-ranked GSEA", total=len(cluster_kd_dict)):
        cluster_prerank_results = Parallel(n_jobs=n_jobs_parallel)(
            delayed(prerank_gsea_cluster_kds)(
                    cluster_label=cluster,
                    cluster_kds=cluster_kd_dict[cluster], 
                    DE_results=DE_results, 
                    gene_set_lib=gene_set_lib, 
                    rank_by=rank_by,
                    min_term_size=min_term_size, 
                    max_term_size=max_term_size, 
                    permutation_num=permutation_num, 
                    n_cpus_per_cluster=n_cpus_per_cluster,
                    random_seed=random_seed, 
                    verbose=verbose)
                for cluster in cluster_kd_dict
            )
    prerank_results_df = pd.concat(cluster_prerank_results)
    return prerank_results_df

def find_cluster_shared_gsea_terms(prerank_results_df: pd.DataFrame,
                                   cluster_label: int | str | None = None,
                                   min_cluster_kds: int=3,
                                   cluster_col: str="Cluster", 
                                   fdr_cutoff: float=0.05,
                                   fdr_col: str="FDR q-val",
                                   min_absolute_nes: None | float = None, 
                                   nes_col: str="NES"
                                   ) -> pd.DataFrame:
    # If cluster_label is provided, look at only that cluster
    # Otherwise look at all clusters and return a combined DF
    pass